from django.urls import path
from . import views

urlpatterns = [
    path('', views.project_list, name='project_list'),
    path('create/', views.project_create, name='project_create'),
    path('update/<int:pk>/', views.project_update, name='project_update'),
    path('delete/<int:pk>/', views.project_delete, name='project_delete'),
    path('api/project/<int:pk>/', views.project_detail_api, name='project_detail_api'),
    path('reorder/', views.reorder_projects, name='reorder_projects'),
    path('update-status/<int:pk>/', views.update_project_status, name='update_project_status'),
    path('update-priority/<int:pk>/', views.update_project_priority, name='update_project_priority'),
    path('set-sort/', views.set_sort, name='set_sort'),
    path('set-group/', views.set_group, name='set_group'),
    path('swap-type-order/', views.swap_type_order, name='swap_type_order'),
    path('project/<int:pk>/', views.project_detail, name='project_detail'),
    path('api/project/<int:project_id>/section/create/', views.create_section, name='create_section'),
    path('api/section/<int:section_id>/task/create/', views.create_task, name='create_task'),
    path('api/task/<int:task_id>/update/', views.update_task_api, name='update_task_api'),
    path('api/task/<int:task_id>/delete/', views.delete_task_api, name='delete_task_api'),
    path('api/section/<int:section_id>/delete/', views.delete_section_api, name='delete_section_api'),
    path('api/section/<int:section_id>/update/', views.update_section_api, name='update_section_api'),
    path('api/project/<int:project_id>/update-name/', views.update_project_name_api, name='update_project_name_api'),
    path('api/project/<int:project_id>/set-next-task/', views.set_next_task_api, name='set_next_task_api'),
    path('api/project/<int:project_id>/status/create/', views.create_status_api, name='create_status_api'),
    path('api/status/<int:status_id>/update/', views.update_status_api, name='update_status_api'),
    path('api/status/<int:status_id>/delete/', views.delete_status_api, name='delete_status_api'),
    path('api/task/reorder/', views.reorder_tasks_api, name='reorder_tasks_api'),
    path('api/section/reorder/', views.reorder_sections_api, name='reorder_sections_api'),
    path('api/section/<int:section_id>/set-sort/', views.update_section_sort_api, name='update_section_sort_api'),
]
