# Generated by Django 4.2.30 on 2026-04-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='manual_status',
            field=models.CharField(blank=True, choices=[('ongoing', 'Ongoing'), ('ontrack', 'On Track'), ('atrisk', 'At Risk'), ('overdue', 'Overdue')], max_length=20, null=True),
        ),
    ]
