# Generated by Django 4.2.30 on 2026-04-15 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectpriority_projectstatus_projecttype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('label', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('label', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_definitions', to='projects.profile')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('profile', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='TypeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('color', models.CharField(default='#BA7517', max_length=7)),
                ('order', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_definitions', to='projects.profile')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('profile', 'slug')},
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='manual_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(default='corporate', max_length=20),
        ),
        migrations.DeleteModel(
            name='ProjectPriority',
        ),
        migrations.DeleteModel(
            name='ProjectStatus',
        ),
        migrations.DeleteModel(
            name='ProjectType',
        ),
        migrations.AddField(
            model_name='prioritydefinition',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority_definitions', to='projects.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='prioritydefinition',
            unique_together={('profile', 'slug')},
        ),
    ]
