# Generated by Django 4.2.30 on 2026-04-15 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_prioritydefinition_profile_statusdefinition_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prioritydefinition',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='statusdefinition',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='typedefinition',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='prioritydefinition',
            name='label',
        ),
        migrations.RemoveField(
            model_name='prioritydefinition',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='statusdefinition',
            name='label',
        ),
        migrations.RemoveField(
            model_name='statusdefinition',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='typedefinition',
            name='slug',
        ),
    ]
