# Generated by Django 4.2.30 on 2026-04-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='prioritydefinition',
            name='color',
            field=models.CharField(default='#BA7517', max_length=7),
        ),
        migrations.AddField(
            model_name='statusdefinition',
            name='color',
            field=models.CharField(default='#1D9E75', max_length=7),
        ),
    ]
